### ISSUE TITLE
README links appear to be broken

### ISSUE THREAD

**Issue by AramZS** [khonsulabs/pulldown-cmark-frontmatter#1]
Unclear why there is a change in this repo to move links to internal files to the repo that assumes this repo is named with `_`s instead of `-`s. This repo is named with `-`s and thus the README links are broken.

**Comment by ecton** [comment]
Thank you for reporting this! I've fixed the repo's README.

To be honest, it's been long enough I don't have a good explanation as to how this happened! And clearly, I didn't test clicking my links!

Thank you again!
